spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: update #create, update, none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true

  logging:
    level:
      org.hibernate.SQL: debug

jwt:
  profiles:
    active: prod